[agent]
  interval = "15s"
  round_interval = true
  hostname = "linux-vm-192-168-1-21"

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
[[inputs.mem]]
[[inputs.swap]]
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.net]]
[[inputs.system]]
[[inputs.processes]]
