[agent]
  interval = "15s"
  hostname = "windows-vm-192-168-1-23"

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = ["% Processor Time"]
    Measurement = "win_cpu"
  [[inputs.win_perf_counters.object]]
    ObjectName = "Memory"
    Counters = ["Available Bytes", "Committed Bytes"]
    Measurement = "win_mem"
  [[inputs.win_perf_counters.object]]
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = ["% Free Space", "Free Megabytes"]
    Measurement = "win_disk"
