[agent]
  interval = "15s"
  hostname = "mysql-192-168-1-30"

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"

[[inputs.mysql]]
  servers = ["monitor:MONITOR_PASSWORD@tcp(127.0.0.1:3306)/"]
  metric_version = 2
  gather_process_list = true
  gather_slave_status = true
  gather_table_schema = true
