[agent]
  interval = "15s"
  hostname = "sqlserver-192-168-1-31"

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"

[[inputs.sqlserver]]
  servers = ["Server=127.0.0.1;Port=1433;User Id=monitor;Password=MONITOR_PASSWORD;app name=telegraf;log=1;"]
  query_version = 2
